//
// Generated by Bluespec Compiler, version 2016.03.beta1 (build 34761, 2016-03-16)
//
// On Sat Jul  9 18:53:29 EDT 2016
//
//
// Ports:
// Name                         I/O  size props
// valid                          O     1
// word                           O    32
// exc                            O     1
// exc_code                       O     4
// cable_ifc_req_enabled          O     1
// cable_ifc_req_arg_op           O     1
// cable_ifc_req_arg_f3           O     3
// cable_ifc_req_arg_addr         O    32
// cable_ifc_req_arg_st_value     O    32
// CLK                            I     1 unused
// RST_N                          I     1 unused
// req_op                         I     1
// req_f3                         I     3
// req_addr                       I    32
// req_st_value                   I    32
// cable_ifc_valid_result_valid   I     1
// cable_ifc_word_result_word     I    32
// cable_ifc_exc_result_exc       I     1
// cable_ifc_exc_code_result_exc_code  I     4
// EN_req                         I     1
//
// Combinational paths from inputs to outputs:
//   (req_op, EN_req) -> cable_ifc_req_arg_op
//   (req_f3, EN_req) -> cable_ifc_req_arg_f3
//   (req_addr, EN_req) -> cable_ifc_req_arg_addr
//   (req_st_value, EN_req) -> cable_ifc_req_arg_st_value
//   cable_ifc_valid_result_valid -> valid
//   cable_ifc_word_result_word -> word
//   cable_ifc_exc_result_exc -> exc
//   cable_ifc_exc_code_result_exc_code -> exc_code
//   EN_req -> cable_ifc_req_enabled
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDCache_Socket(CLK,
		       RST_N,

		       req_op,
		       req_f3,
		       req_addr,
		       req_st_value,
		       EN_req,

		       valid,

		       word,

		       exc,

		       exc_code,

		       cable_ifc_req_enabled,

		       cable_ifc_req_arg_op,

		       cable_ifc_req_arg_f3,

		       cable_ifc_req_arg_addr,

		       cable_ifc_req_arg_st_value,

		       cable_ifc_valid_result_valid,

		       cable_ifc_word_result_word,

		       cable_ifc_exc_result_exc,

		       cable_ifc_exc_code_result_exc_code);
  input  CLK;
  input  RST_N;

  // action method req
  input  req_op;
  input  [2 : 0] req_f3;
  input  [31 : 0] req_addr;
  input  [31 : 0] req_st_value;
  input  EN_req;

  // value method valid
  output valid;

  // value method word
  output [31 : 0] word;

  // value method exc
  output exc;

  // value method exc_code
  output [3 : 0] exc_code;

  // value method cable_ifc_req_enabled
  output cable_ifc_req_enabled;

  // value method cable_ifc_req_arg_op
  output cable_ifc_req_arg_op;

  // value method cable_ifc_req_arg_f3
  output [2 : 0] cable_ifc_req_arg_f3;

  // value method cable_ifc_req_arg_addr
  output [31 : 0] cable_ifc_req_arg_addr;

  // value method cable_ifc_req_arg_st_value
  output [31 : 0] cable_ifc_req_arg_st_value;

  // action method cable_ifc_valid_result
  input  cable_ifc_valid_result_valid;

  // action method cable_ifc_word_result
  input  [31 : 0] cable_ifc_word_result_word;

  // action method cable_ifc_exc_result
  input  cable_ifc_exc_result_exc;

  // action method cable_ifc_exc_code_result
  input  [3 : 0] cable_ifc_exc_code_result_exc_code;

  // signals for module outputs
  wire [31 : 0] cable_ifc_req_arg_addr, cable_ifc_req_arg_st_value, word;
  wire [3 : 0] exc_code;
  wire [2 : 0] cable_ifc_req_arg_f3;
  wire cable_ifc_req_arg_op, cable_ifc_req_enabled, exc, valid;

  // rule scheduling signals
  wire CAN_FIRE_cable_ifc_exc_code_result,
       CAN_FIRE_cable_ifc_exc_result,
       CAN_FIRE_cable_ifc_valid_result,
       CAN_FIRE_cable_ifc_word_result,
       CAN_FIRE_req,
       WILL_FIRE_cable_ifc_exc_code_result,
       WILL_FIRE_cable_ifc_exc_result,
       WILL_FIRE_cable_ifc_valid_result,
       WILL_FIRE_cable_ifc_word_result,
       WILL_FIRE_req;

  // action method req
  assign CAN_FIRE_req = 1'd1 ;
  assign WILL_FIRE_req = EN_req ;

  // value method valid
  assign valid = cable_ifc_valid_result_valid ;

  // value method word
  assign word = cable_ifc_word_result_word ;

  // value method exc
  assign exc = cable_ifc_exc_result_exc ;

  // value method exc_code
  assign exc_code = cable_ifc_exc_code_result_exc_code ;

  // value method cable_ifc_req_enabled
  assign cable_ifc_req_enabled = EN_req ;

  // value method cable_ifc_req_arg_op
  assign cable_ifc_req_arg_op = req_op ;

  // value method cable_ifc_req_arg_f3
  assign cable_ifc_req_arg_f3 = req_f3 ;

  // value method cable_ifc_req_arg_addr
  assign cable_ifc_req_arg_addr = req_addr ;

  // value method cable_ifc_req_arg_st_value
  assign cable_ifc_req_arg_st_value = req_st_value ;

  // action method cable_ifc_valid_result
  assign CAN_FIRE_cable_ifc_valid_result = 1'd1 ;
  assign WILL_FIRE_cable_ifc_valid_result = 1'd1 ;

  // action method cable_ifc_word_result
  assign CAN_FIRE_cable_ifc_word_result = 1'd1 ;
  assign WILL_FIRE_cable_ifc_word_result = 1'd1 ;

  // action method cable_ifc_exc_result
  assign CAN_FIRE_cable_ifc_exc_result = 1'd1 ;
  assign WILL_FIRE_cable_ifc_exc_result = 1'd1 ;

  // action method cable_ifc_exc_code_result
  assign CAN_FIRE_cable_ifc_exc_code_result = 1'd1 ;
  assign WILL_FIRE_cable_ifc_exc_code_result = 1'd1 ;
endmodule  // mkDCache_Socket

