/*
 * Generated by Bluespec Compiler, version 2016.03.beta1 (build 34761, 2016-03-16)
 * 
 * On Thu Jul  7 14:37:16 EDT 2016
 * 
 */
#ifndef __vpi_wrapper_bsv_mem_read16_h__
#define __vpi_wrapper_bsv_mem_read16_h__

#include <vpi_user.h>

/* registration function */
void bsv_mem_read16_vpi_register();

/* VPI wrapper function */
PLI_INT32 bsv_mem_read16_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_bsv_mem_read16_h__ */
