/*
 * Generated by Bluespec Compiler, version 2016.03.beta1 (build 34761, 2016-03-16)
 * 
 * On Thu Jul  7 14:37:16 EDT 2016
 * 
 */
#ifndef __vpi_wrapper_c_trygetchar_h__
#define __vpi_wrapper_c_trygetchar_h__

#include <vpi_user.h>

/* registration function */
void c_trygetchar_vpi_register();

/* VPI wrapper function */
PLI_INT32 c_trygetchar_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_c_trygetchar_h__ */
