/*
 * Generated by Bluespec Compiler, version 2016.03.beta1 (build 34761, 2016-03-16)
 * 
 * On Thu Jul  7 14:39:33 EDT 2016
 * 
 */

/* registration array */
#include "vpi_wrapper_bsv_mem_get_exit_pc.h"
#include "vpi_wrapper_bsv_mem_get_max_addr.h"
#include "vpi_wrapper_bsv_mem_get_min_addr.h"
#include "vpi_wrapper_bsv_mem_init.h"
#include "vpi_wrapper_bsv_mem_load_elf2.h"
#include "vpi_wrapper_bsv_mem_read32.h"
#include "vpi_wrapper_c_getenv_u64.h"
#include "vpi_wrapper_c_putchar.h"
#include "vpi_wrapper_c_trygetchar.h"

/* Convenience function to register all imported functions */
void vpi_register_all()
{
  bsv_mem_get_exit_pc_vpi_register();
  bsv_mem_get_max_addr_vpi_register();
  bsv_mem_get_min_addr_vpi_register();
  bsv_mem_init_vpi_register();
  bsv_mem_load_elf2_vpi_register();
  bsv_mem_read32_vpi_register();
  c_getenv_u64_vpi_register();
  c_putchar_vpi_register();
  c_trygetchar_vpi_register();
}

/* Convenience function to register only tasks */
void vpi_register_tasks()
{
  c_putchar_vpi_register();
}
void (*vlog_startup_routines[])() = { vpi_register_all, 0u };
